name: Link Jira issues
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  change-pr-name:
    name: Change Pull Request name
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout ${GITHUB_BASE_REF}
        git checkout ${GITHUB_HEAD_REF}
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
      id: extract_branch

    - name: Remove old link
      shell: bash
      run: echo "##[set-output name=title;]$(echo "${{ github.event.pull_request.title }}" | sed 's/\[.*\] - //')"
      id: clean_title

    - name: Generate pull request title
      shell: bash
      run: echo "##[set-output name=title;]$(git log ${GITHUB_BASE_REF#refs/heads/}..${{ steps.extract_branch.outputs.branch }} --no-merges --grep='YURI2' | grep -Eo 'YURI2-[0-9]{1,10}' | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}' | tr " " "," | sed 's/.$/] - ${{ steps.clean_title.outputs.title }}/' | sed 's/^/[/' | sed 's/,/, /')"
      id: generate_title

    - name: PR title updater
      uses: juztcode/pr-updater@1.0.0
      with:
        title: ${{ steps.generate_title.outputs.title }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      if: ${{ failure() }}
      with:
        message: |
          :exclamation::exclamation: Você esqueceu de colocar o código da(s) subtask(s) nas mensagens de commit :exclamation::exclamation:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
